# Generated by Django 3.2.5 on 2021-07-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Programmer',
        ),
    ]
