# Generated by Django 3.2.6 on 2022-01-24 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_rename_languages_programmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='c_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='c_plus_plus_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='java_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='python_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='rust_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
