# Generated by Django 3.2.5 on 2022-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20220124_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='c_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='c_plus_plus_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='java_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='python_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='rust_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
    ]
